package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Ultra-Clean Luxury White Pro Palette (Apple / OpenAI / Gemini Inspired)
val PureWhite = Color(0xFFFFFFFF)
val SnowCanvas = Color(0xFFF8FAFC)
val SoftMist = Color(0xFFF1F5F9)
val SlateBorder = Color(0xFFE2E8F0)
val SlateBorderSubtle = Color(0xFFEDF2F7)
val SlateMuted = Color(0xFF94A3B8)
val SlateText = Color(0xFF64748B)
val SlateTextDark = Color(0xFF334155)
val ObsidianText = Color(0xFF0F172A)
val CharcoalHeader = Color(0xFF1E293B)

// Executive Tech Accents (Sapphire & Electric Violet & Emerald Glow)
val RoyalSapphire = Color(0xFF2563EB)
val RoyalSapphireDark = Color(0xFF1D4ED8)
val RoyalSapphireLight = Color(0xFF3B82F6)
val RoyalSapphireBg = Color(0xFFEFF6FF)
val ElectricViolet = Color(0xFF6366F1)
val ElectricVioletLight = Color(0xFF818CF8)
val EmeraldGlow = Color(0xFF10B981)
val EmeraldBg = Color(0xFFECFDF5)
val AmberGlow = Color(0xFFF59E0B)
val AmberBg = Color(0xFFFFFBEB)
val RoseGlow = Color(0xFFEF4444)
val RoseBg = Color(0xFFFEF2F2)
val CyanAccent = Color(0xFF06B6D4)

// Dark Theme Surfaces (Deep Tech Obsidian)
val DarkBackground = Color(0xFF0B0F19)
val DarkSurface = Color(0xFF111827)
val DarkSurfaceVariant = Color(0xFF1F2937)
val DarkSurfaceElevated = Color(0xFF283548)
val DarkCardBorder = Color(0xFF374151)
val DarkTextPrimary = Color(0xFFF9FAFB)
val DarkTextSecondary = Color(0xFF9CA3AF)
val DarkUserBubble = Color(0xFF1E40AF)
val DarkUserBubbleEnd = Color(0xFF1D4ED8)
val DarkAssistantBubble = Color(0xFF111827)
val DarkCodeBackground = Color(0xFF0B1120)

// Light Theme Surfaces (Pure White Luxury High-Contrast)
val LightBackground = Color(0xFFF8FAFC)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightSurfaceElevated = Color(0xFFFFFFFF)
val LightCardBorder = Color(0xFFE2E8F0)
val LightTextPrimary = Color(0xFF0F172A)
val LightTextSecondary = Color(0xFF475569)
val LightUserBubble = Color(0xFF2563EB)
val LightUserBubbleEnd = Color(0xFF1D4ED8)
val LightAssistantBubble = Color(0xFFFFFFFF)
val LightCodeBackground = Color(0xFF0F172A)


